/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/2k_lan_down.png */
extern const unsigned char resico_2k_lan_down[];

/* created by reswrap from file res/2k_lan_idle.png */
extern const unsigned char resico_2k_lan_idle[];

/* created by reswrap from file res/2k_lan_rx.png */
extern const unsigned char resico_2k_lan_rx[];

/* created by reswrap from file res/2k_lan_tx.png */
extern const unsigned char resico_2k_lan_tx[];

/* created by reswrap from file res/2k_lan_txrx.png */
extern const unsigned char resico_2k_lan_txrx[];

/* created by reswrap from file res/2k_wlan_down.png */
extern const unsigned char resico_2k_wlan_down[];

/* created by reswrap from file res/2k_wlan_idle.png */
extern const unsigned char resico_2k_wlan_idle[];

/* created by reswrap from file res/2k_wlan_rx.png */
extern const unsigned char resico_2k_wlan_rx[];

/* created by reswrap from file res/2k_wlan_tx.png */
extern const unsigned char resico_2k_wlan_tx[];

/* created by reswrap from file res/2k_wlan_txrx.png */
extern const unsigned char resico_2k_wlan_txrx[];

/* created by reswrap from file res/xp_lan_down.png */
extern const unsigned char resico_xp_lan_down[];

/* created by reswrap from file res/xp_lan_idle.png */
extern const unsigned char resico_xp_lan_idle[];

/* created by reswrap from file res/xp_lan_rx.png */
extern const unsigned char resico_xp_lan_rx[];

/* created by reswrap from file res/xp_lan_tx.png */
extern const unsigned char resico_xp_lan_tx[];

/* created by reswrap from file res/xp_lan_txrx.png */
extern const unsigned char resico_xp_lan_txrx[];

/* created by reswrap from file res/xp_wlan_down.png */
extern const unsigned char resico_xp_wlan_down[];

/* created by reswrap from file res/xp_wlan_idle.png */
extern const unsigned char resico_xp_wlan_idle[];

/* created by reswrap from file res/xp_wlan_rx.png */
extern const unsigned char resico_xp_wlan_rx[];

/* created by reswrap from file res/xp_wlan_tx.png */
extern const unsigned char resico_xp_wlan_tx[];

/* created by reswrap from file res/xp_wlan_txrx.png */
extern const unsigned char resico_xp_wlan_txrx[];

