#!/bin/sh
if [ "$1" = "low" ]; then
	notify-send -u low "Low Battery" "You should change your battery or switch to outlet power immediately to keep from losing your work."
elif [ "$1" = "critical" ]; then
	notify-send -u critical "Critical Battery" "You should change your battery or switch to outlet power immediately to keep from losing your work."
fi
