/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/globe.gif */
extern const unsigned char resico_globe[];

/* created by reswrap from file res/mainicon.gif */
extern const unsigned char resico_mainicon[];

