/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/mainicon.gif */
extern const unsigned char resico_mainicon[];

/* created by reswrap from file res/user.gif */
extern const unsigned char resico_user[];

/* created by reswrap from file res/authbanner.png */
extern const unsigned char resico_authbanner[];

