/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/2klan.gif */
extern const unsigned char resico_2klan[];

/* created by reswrap from file res/adhoc.gif */
extern const unsigned char resico_adhoc[];

/* created by reswrap from file res/adhoc_c.gif */
extern const unsigned char resico_adhoc_c[];

/* created by reswrap from file res/adhoc_h.gif */
extern const unsigned char resico_adhoc_h[];

/* created by reswrap from file res/infra.gif */
extern const unsigned char resico_infra[];

/* created by reswrap from file res/infra_c.gif */
extern const unsigned char resico_infra_c[];

/* created by reswrap from file res/infra_h.gif */
extern const unsigned char resico_infra_h[];

/* created by reswrap from file res/mainicon.gif */
extern const unsigned char resico_mainicon[];

/* created by reswrap from file res/nosel.gif */
extern const unsigned char resico_nosel[];

/* created by reswrap from file res/sel.gif */
extern const unsigned char resico_sel[];

/* created by reswrap from file res/xplan.gif */
extern const unsigned char resico_xplan[];

