/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/mainicon.png */
extern const unsigned char resico_mainicon[];

/* created by reswrap from file res/ncpa/2k_ncpa_dial.png */
extern const unsigned char resico_2k_ncpa_dial[];

/* created by reswrap from file res/ncpa/2k_ncpa_dial_down.png */
extern const unsigned char resico_2k_ncpa_dial_down[];

/* created by reswrap from file res/ncpa/2k_ncpa_dial_idle.png */
extern const unsigned char resico_2k_ncpa_dial_idle[];

/* created by reswrap from file res/ncpa/2k_ncpa_dial_nohw.png */
extern const unsigned char resico_2k_ncpa_dial_nohw[];

/* created by reswrap from file res/ncpa/2k_ncpa_dial_rx.png */
extern const unsigned char resico_2k_ncpa_dial_rx[];

/* created by reswrap from file res/ncpa/2k_ncpa_dial_tx.png */
extern const unsigned char resico_2k_ncpa_dial_tx[];

/* created by reswrap from file res/ncpa/2k_ncpa_dial_txrx.png */
extern const unsigned char resico_2k_ncpa_dial_txrx[];

/* created by reswrap from file res/ncpa/2k_ncpa_direct.png */
extern const unsigned char resico_2k_ncpa_direct[];

/* created by reswrap from file res/ncpa/2k_ncpa_direct_down.png */
extern const unsigned char resico_2k_ncpa_direct_down[];

/* created by reswrap from file res/ncpa/2k_ncpa_direct_idle.png */
extern const unsigned char resico_2k_ncpa_direct_idle[];

/* created by reswrap from file res/ncpa/2k_ncpa_direct_rx.png */
extern const unsigned char resico_2k_ncpa_direct_rx[];

/* created by reswrap from file res/ncpa/2k_ncpa_direct_tx.png */
extern const unsigned char resico_2k_ncpa_direct_tx[];

/* created by reswrap from file res/ncpa/2k_ncpa_direct_txrx.png */
extern const unsigned char resico_2k_ncpa_direct_txrx[];

/* created by reswrap from file res/ncpa/2k_ncpa_lan.png */
extern const unsigned char resico_2k_ncpa_lan[];

/* created by reswrap from file res/ncpa/2k_ncpa_lan_down.png */
extern const unsigned char resico_2k_ncpa_lan_down[];

/* created by reswrap from file res/ncpa/2k_ncpa_lan_idle.png */
extern const unsigned char resico_2k_ncpa_lan_idle[];

/* created by reswrap from file res/ncpa/2k_ncpa_lan_nohw.png */
extern const unsigned char resico_2k_ncpa_lan_nohw[];

/* created by reswrap from file res/ncpa/2k_ncpa_lan_rx.png */
extern const unsigned char resico_2k_ncpa_lan_rx[];

/* created by reswrap from file res/ncpa/2k_ncpa_lan_tx.png */
extern const unsigned char resico_2k_ncpa_lan_tx[];

/* created by reswrap from file res/ncpa/2k_ncpa_lan_txrx.png */
extern const unsigned char resico_2k_ncpa_lan_txrx[];

/* created by reswrap from file res/ncpa/2k_ncpa_vpn.png */
extern const unsigned char resico_2k_ncpa_vpn[];

/* created by reswrap from file res/ncpa/2k_ncpa_vpn_idle.png */
extern const unsigned char resico_2k_ncpa_vpn_idle[];

/* created by reswrap from file res/ncpa/2k_ncpa_vpn_rx.png */
extern const unsigned char resico_2k_ncpa_vpn_rx[];

/* created by reswrap from file res/ncpa/2k_ncpa_vpn_tx.png */
extern const unsigned char resico_2k_ncpa_vpn_tx[];

/* created by reswrap from file res/ncpa/2k_ncpa_vpn_txrx.png */
extern const unsigned char resico_2k_ncpa_vpn_txrx[];

/* created by reswrap from file res/xpncpa/xp_ncpa_dial.png */
extern const unsigned char resico_xp_ncpa_dial[];

/* created by reswrap from file res/xpncpa/xp_ncpa_dial_down.png */
extern const unsigned char resico_xp_ncpa_dial_down[];

/* created by reswrap from file res/xpncpa/xp_ncpa_dial_idle.png */
extern const unsigned char resico_xp_ncpa_dial_idle[];

/* created by reswrap from file res/xpncpa/xp_ncpa_dial_nohw.png */
extern const unsigned char resico_xp_ncpa_dial_nohw[];

/* created by reswrap from file res/xpncpa/xp_ncpa_dial_rx.png */
extern const unsigned char resico_xp_ncpa_dial_rx[];

/* created by reswrap from file res/xpncpa/xp_ncpa_dial_tx.png */
extern const unsigned char resico_xp_ncpa_dial_tx[];

/* created by reswrap from file res/xpncpa/xp_ncpa_dial_txrx.png */
extern const unsigned char resico_xp_ncpa_dial_txrx[];

/* created by reswrap from file res/xpncpa/xp_ncpa_direct.png */
extern const unsigned char resico_xp_ncpa_direct[];

/* created by reswrap from file res/xpncpa/xp_ncpa_direct_down.png */
extern const unsigned char resico_xp_ncpa_direct_down[];

/* created by reswrap from file res/xpncpa/xp_ncpa_direct_idle.png */
extern const unsigned char resico_xp_ncpa_direct_idle[];

/* created by reswrap from file res/xpncpa/xp_ncpa_direct_nohw.png */
extern const unsigned char resico_xp_ncpa_direct_nohw[];

/* created by reswrap from file res/xpncpa/xp_ncpa_direct_rx.png */
extern const unsigned char resico_xp_ncpa_direct_rx[];

/* created by reswrap from file res/xpncpa/xp_ncpa_direct_tx.png */
extern const unsigned char resico_xp_ncpa_direct_tx[];

/* created by reswrap from file res/xpncpa/xp_ncpa_direct_txrx.png */
extern const unsigned char resico_xp_ncpa_direct_txrx[];

/* created by reswrap from file res/xpncpa/xp_ncpa_lan.png */
extern const unsigned char resico_xp_ncpa_lan[];

/* created by reswrap from file res/xpncpa/xp_ncpa_lan_down.png */
extern const unsigned char resico_xp_ncpa_lan_down[];

/* created by reswrap from file res/xpncpa/xp_ncpa_lan_idle.png */
extern const unsigned char resico_xp_ncpa_lan_idle[];

/* created by reswrap from file res/xpncpa/xp_ncpa_lan_nohw.png */
extern const unsigned char resico_xp_ncpa_lan_nohw[];

/* created by reswrap from file res/xpncpa/xp_ncpa_lan_rx.png */
extern const unsigned char resico_xp_ncpa_lan_rx[];

/* created by reswrap from file res/xpncpa/xp_ncpa_lan_tx.png */
extern const unsigned char resico_xp_ncpa_lan_tx[];

/* created by reswrap from file res/xpncpa/xp_ncpa_lan_txrx.png */
extern const unsigned char resico_xp_ncpa_lan_txrx[];

/* created by reswrap from file res/xpncpa/xp_ncpa_pppoe.png */
extern const unsigned char resico_xp_ncpa_pppoe[];

/* created by reswrap from file res/xpncpa/xp_ncpa_pppoe_down.png */
extern const unsigned char resico_xp_ncpa_pppoe_down[];

/* created by reswrap from file res/xpncpa/xp_ncpa_pppoe_idle.png */
extern const unsigned char resico_xp_ncpa_pppoe_idle[];

/* created by reswrap from file res/xpncpa/xp_ncpa_pppoe_nohw.png */
extern const unsigned char resico_xp_ncpa_pppoe_nohw[];

/* created by reswrap from file res/xpncpa/xp_ncpa_pppoe_rx.png */
extern const unsigned char resico_xp_ncpa_pppoe_rx[];

/* created by reswrap from file res/xpncpa/xp_ncpa_pppoe_tx.png */
extern const unsigned char resico_xp_ncpa_pppoe_tx[];

/* created by reswrap from file res/xpncpa/xp_ncpa_pppoe_txrx.png */
extern const unsigned char resico_xp_ncpa_pppoe_txrx[];

/* created by reswrap from file res/xpncpa/xp_ncpa_vpn.png */
extern const unsigned char resico_xp_ncpa_vpn[];

/* created by reswrap from file res/xpncpa/xp_ncpa_vpn_down.png */
extern const unsigned char resico_xp_ncpa_vpn_down[];

/* created by reswrap from file res/xpncpa/xp_ncpa_vpn_idle.png */
extern const unsigned char resico_xp_ncpa_vpn_idle[];

/* created by reswrap from file res/xpncpa/xp_ncpa_vpn_nohw.png */
extern const unsigned char resico_xp_ncpa_vpn_nohw[];

/* created by reswrap from file res/xpncpa/xp_ncpa_vpn_rx.png */
extern const unsigned char resico_xp_ncpa_vpn_rx[];

/* created by reswrap from file res/xpncpa/xp_ncpa_vpn_tx.png */
extern const unsigned char resico_xp_ncpa_vpn_tx[];

/* created by reswrap from file res/xpncpa/xp_ncpa_vpn_txrx.png */
extern const unsigned char resico_xp_ncpa_vpn_txrx[];

/* created by reswrap from file res/xpncpa/xp_ncpa_wlan.png */
extern const unsigned char resico_xp_ncpa_wlan[];

/* created by reswrap from file res/xpncpa/xp_ncpa_wlan_down.png */
extern const unsigned char resico_xp_ncpa_wlan_down[];

/* created by reswrap from file res/xpncpa/xp_ncpa_wlan_idle.png */
extern const unsigned char resico_xp_ncpa_wlan_idle[];

/* created by reswrap from file res/xpncpa/xp_ncpa_wlan_nohw.png */
extern const unsigned char resico_xp_ncpa_wlan_nohw[];

/* created by reswrap from file res/xpncpa/xp_ncpa_wlan_rx.png */
extern const unsigned char resico_xp_ncpa_wlan_rx[];

/* created by reswrap from file res/xpncpa/xp_ncpa_wlan_tx.png */
extern const unsigned char resico_xp_ncpa_wlan_tx[];

/* created by reswrap from file res/xpncpa/xp_ncpa_wlan_txrx.png */
extern const unsigned char resico_xp_ncpa_wlan_txrx[];

