#!/bin/sh

if mountpoint -q -- "$*"; then
	aplay -q "$ICE2KSYS_SOUND_ERROR" &
	>&2 echo "Already mounted!"
	exit 1
else
	if mount "$@" 1> /dev/null 2> /dev/null; then
		exit
	else
		i2ksudo mount "$@"
	fi
fi

