#!/bin/sh

if mountpoint -q -- "$*"; then
	if umount "$@" 1> /dev/null 2> /dev/null; then
		exit
	else
		i2ksudo umount "$@"
	fi
else
	aplay -q "$ICE2KSYS_SOUND_ERROR" &
	>&2 echo "Not mounted!"
	exit 1
fi
