/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/batcrit.gif */
extern const unsigned char resico_batcrit[];

/* created by reswrap from file res/batfull.gif */
extern const unsigned char resico_batfull[];

/* created by reswrap from file res/bathalf.gif */
extern const unsigned char resico_bathalf[];

/* created by reswrap from file res/batlow.gif */
extern const unsigned char resico_batlow[];

/* created by reswrap from file res/battery.gif */
extern const unsigned char resico_battery[];

/* created by reswrap from file res/battplug.gif */
extern const unsigned char resico_battplug[];

/* created by reswrap from file res/charging.gif */
extern const unsigned char resico_charging[];

/* created by reswrap from file res/notpres.gif */
extern const unsigned char resico_notpres[];

/* created by reswrap from file res/plug.gif */
extern const unsigned char resico_plug[];

/* created by reswrap from file res/unknown.gif */
extern const unsigned char resico_unknown[];

