#!/bin/sh
while LC_ALL=C iwctl station $@ show | grep -q "Scanning            yes"
do
	sleep 2
done

netlistcon="$(iwctl station $@ get-networks rssi-dbms | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g" | cut -c 3- | tail -n +5 | head -n -1 )"
netlist="$(echo "$netlistcon" | cut -c 3- )"
netnumber="$(echo "$netlist" | wc -l)"
#echo "$netlistcon"
#echo
#echo "$netlist" | sed 's/..... *$//' | sed 's/[[:blank:]]*$//' | sed 's/..... *$//' | sed 's/[[:blank:]]*$//'

dbms() {
	if [ $dbms -ge -6000 ]; then
	        echo "network-wireless-100"
	elif [ $dbms -ge -6700 ]; then
	        echo "network-wireless-75"
	elif [ $dbms -ge -7500 ]; then
	        echo "network-wireless-50"
	elif [ $dbms -lt -7500 ]; then
	        echo "network-wireless-25"
	fi
}

for i in $(seq -s " " 1 $netnumber); do
	export dbms="$(echo "$netlist" | awk 'NF>1{print $NF}' | sed -n "${i}p")"
	dbms
	echo "$netlistcon" | cut -c 1 | sed -n "${i}p"
	echo "$netlist" | sed -n "${i}p" | sed 's/....................... *$//' | sed 's/[[:blank:]]*$//'
	echo "$netlist" | sed -n "${i}p" | sed 's/..... *$//' | sed 's/[[:blank:]]*$//' |  awk 'NF>1{print $NF}'
done

#echo "$netlist" | awk 'NF>1{print $NF}'

#echo "$netlist"
