/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/2k_eject.png */
extern const unsigned char resico_2k_eject[];

/* created by reswrap from file res/xp_eject.png */
extern const unsigned char resico_xp_eject[];

