/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/ico_main_16.gif */
extern const unsigned char res_ico_main_16[];

/* created by reswrap from file res/img_coolmine.gif */
extern const unsigned char res_img_coolmine[];

/* created by reswrap from file res/img_coolsmil.gif */
extern const unsigned char res_img_coolsmil[];

/* created by reswrap from file res/img_segment.gif */
extern const unsigned char res_img_segment[];

