/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/ico_mainicon.gif */
extern const unsigned char res_ico_mainicon[];

/* created by reswrap from file res/img_connect.gif */
extern const unsigned char res_img_connect[];

/* created by reswrap from file res/img_discover.gif */
extern const unsigned char res_img_discover[];

/* created by reswrap from file res/img_logo.gif */
extern const unsigned char res_img_logo[];

/* created by reswrap from file res/img_register.gif */
extern const unsigned char res_img_register[];

/* created by reswrap from file res/img_welcome.gif */
extern const unsigned char res_img_welcome[];

