/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/connect.gif */
extern const unsigned char resico_connect[];

/* created by reswrap from file res/discover.gif */
extern const unsigned char resico_discover[];

/* created by reswrap from file res/logo.gif */
extern const unsigned char resico_logo[];

/* created by reswrap from file res/mainicon.gif */
extern const unsigned char resico_mainicon[];

/* created by reswrap from file res/register.gif */
extern const unsigned char resico_register[];

/* created by reswrap from file res/welcome.gif */
extern const unsigned char resico_welcome[];

