/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/connect.gif */
extern const unsigned char resico_connect[];

/* created by reswrap from file res/info.gif */
extern const unsigned char resico_info[];

/* created by reswrap from file res/mainicon.gif */
extern const unsigned char resico_mainicon[];

/* created by reswrap from file res/scanning.gif */
extern const unsigned char resico_scanning[];

/* created by reswrap from file res/wifi0.gif */
extern const unsigned char resico_wifi0[];

/* created by reswrap from file res/wifi1.gif */
extern const unsigned char resico_wifi1[];

/* created by reswrap from file res/wifi2.gif */
extern const unsigned char resico_wifi2[];

/* created by reswrap from file res/wifi3.gif */
extern const unsigned char resico_wifi3[];

/* created by reswrap from file res/wifi4.gif */
extern const unsigned char resico_wifi4[];

/* created by reswrap from file res/wizicon.gif */
extern const unsigned char resico_wizicon[];

/* created by reswrap from file res/wizicon2.gif */
extern const unsigned char resico_wizicon2[];

