/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/ico_main32.gif */
extern const unsigned char res_ico_main32[];

/* created by reswrap from file res/img_bombspr.gif */
extern const unsigned char res_img_bombspr[];

