/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/2k_powercfg_16.png */
extern const unsigned char resico_2k_powercfg_16[];

/* created by reswrap from file res/2k_powercfg_32.png */
extern const unsigned char resico_2k_powercfg_32[];

/* created by reswrap from file res/xp_powercfg_16.png */
extern const unsigned char resico_xp_powercfg_16[];

/* created by reswrap from file res/xp_powercfg_32.png */
extern const unsigned char resico_xp_powercfg_32[];

