/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/2k_error.gif */
extern const unsigned char resico_2k_error[];

/* created by reswrap from file res/mainicon.gif */
extern const unsigned char resico_mainicon[];

/* created by reswrap from file res/xp_error.png */
extern const unsigned char resico_xp_error[];

