/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/bmpfont.gif */
extern const unsigned char resico_bmpfont[];

/* created by reswrap from file res/ttffont.gif */
extern const unsigned char resico_ttffont[];

