/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file res/ico_main_16_2k.png */
extern const unsigned char res_ico_main_16_2k[];

/* created by reswrap from file res/ico_main_16_xp.png */
extern const unsigned char res_ico_main_16_xp[];

/* created by reswrap from file res/ico_main_32_2k.png */
extern const unsigned char res_ico_main_32_2k[];

/* created by reswrap from file res/ico_main_32_xp.png */
extern const unsigned char res_ico_main_32_xp[];

/* created by reswrap from file res/img_coolmine.gif */
extern const unsigned char res_img_coolmine[];

/* created by reswrap from file res/img_coolseg.gif */
extern const unsigned char res_img_coolseg[];

/* created by reswrap from file res/img_coolsmil.gif */
extern const unsigned char res_img_coolsmil[];

/* created by reswrap from file res/img_monomine.gif */
extern const unsigned char res_img_monomine[];

/* created by reswrap from file res/img_monoseg.gif */
extern const unsigned char res_img_monoseg[];

/* created by reswrap from file res/img_monosmil.gif */
extern const unsigned char res_img_monosmil[];

